### PR TITLE
Add support for nice mocks

### PR DESCRIPTION
**Pull request by APokorny**
Nice mocks do not complain when a method is called that is not expected. This is similar to the nice mock concept in GMock. To make use of that feature, just use `NiceMock<Type>()` instead of `Mock<Type>()`.

### CODE REVIEW

**Comment by APokorny** [comment]
I based this proposal on the unique_ptr change because it touches the same code, and I think both are very useful..

**Comment by dascandy** [comment]
... Not looking at the build results so much, but how is this supposed to work? The called function cannot know what arguments there are so it can't remove them from the stack in callee-cleanup environments (MSVC).

**Comment by APokorny** [comment]
Build failed due to a missing file  - but yes this is more than undefined behavior.

**Comment by APokorny** [comment]
I think this is extremely helpful when you construct mocks inside fixtures.. 
Do you have any ideas on how to make that portable?

**Comment by dascandy** [comment]
1. This is very quickly undefined behaviour & crashing if you call a function that has a nontrivial return type
2. This cannot be ported to Windows for anything other than functions without arguments
3. Even in the case that you have a trivial return type, the return value is undefined

So this only actually allows you to call functions that have no return value on non-Windows, or functions that have no return value with no arguments reliably. Functions with a trivial return value will "work" but return uninitialized memory (so pointers are whatever rax held at the time of calling, floats can be NaN or denormal accidentally - or heck, an uninitialized FP register causing the FP stack to be unbalanced, other things).

This is why it was not added before.

**Comment by APokorny** [comment]
Ok all in all a bad idea without reflection.. 
So I will look into making it easy to specify a list of ignored methods..

**Pull request closed without merging**
